using Slic3rPostProcessingUploader.Services.Parsers;
using Slic3rPostProcessingUploader.Services.Parsers.Computed;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers.Computed
{
    /// <summary>
    /// PrusaSlicer G-code carries no list of changed settings, but a user preset's .ini file is a full dump of the
    /// preset, so a key whose G-code value differs from the saved one is an unsaved plater change. The placeholder
    /// checks each preset type (print, every filament slot, printer) against the user's own files and reports what
    /// it can prove; a preset with no readable file (a system preset, another machine) is skipped, never guessed.
    /// </summary>
    [TestClass]
    public class PrusaModifiedSettingsPlaceholderTests
    {
        private string root = null!;
        private readonly List<string> log = [];

        [TestInitialize]
        public void CreateRoot()
        {
            root = Path.Combine(Path.GetTempPath(), "uploader-prusa-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(root);
        }

        [TestCleanup]
        public void DeleteRoot()
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }

        private void WritePreset(string type, string name, string ini, string? configRoot = null)
        {
            var dir = Path.Combine(configRoot ?? root, type);
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, name + ".ini"), "# generated by PrusaSlicer 2.9.2 on 2025-01-01\n" + ini);
        }

        private string Render(string gcode, params string[] roots)
        {
            var settings = GcodeSettings.Parse(gcode, "=");
            var options = new ParseOptions(ParseOptions.InMemory(gcode).OpenFullGcode, log.Add, () => roots.Length == 0 ? [root] : roots);
            return PrusaModifiedSettingsPlaceholder.Instance.Render(new ComputedContext(settings, options));
        }

        private const string Ids = "; print_settings_id = My Print\n; filament_settings_id = \"My PLA\"\n; printer_settings_id = My Printer\n";

        [TestMethod]
        public void ShouldListPrintKeysWhoseGcodeValueDiffersFromTheSavedPreset()
        {
            WritePreset("print", "My Print", "fill_density = 15%\nlayer_height = 0.2\nperimeters = 2\n");

            var note = Render(Ids + "; fill_density = 25%\n; layer_height = 0.2\n; perimeters = 3\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: fill_density = 25%, perimeters = 3\n", note);
        }

        [TestMethod]
        public void ShouldReportASavedValueThatWasClearedInThePlater()
        {
            WritePreset("print", "My Print", "notes = keep me\nfill_density = 15%\n");

            var note = Render(Ids + "; notes = \n; fill_density = 15%\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: notes = \n", note);
        }

        [TestMethod]
        public void ShouldRenderNothingWhenEveryValueMatchesTheSavedPreset()
        {
            WritePreset("print", "My Print", "fill_density = 15%\nlayer_height = 0.2\n");

            Assert.AreEqual(string.Empty, Render(Ids + "; fill_density = 15%\n; layer_height = 0.2\n"));
        }

        [TestMethod]
        public void ShouldCompareFilamentKeysSlotBySlotAgainstEachSlotsPreset()
        {
            WritePreset("filament", "My PLA", "temperature = 215\nfilament_type = PLA\nfilament_notes = \"\"\n");
            WritePreset("filament", "My PETG", "temperature = 240\nfilament_type = PETG\nfilament_notes = \"\"\n");

            var note = Render(
                "; filament_settings_id = \"My PLA\";\"My PETG\"\n" +
                "; temperature = 215,250\n" +
                "; filament_type = PLA;PETG\n" +
                "; filament_notes = \"\";\"\"\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: temperature = 215,250\n", note);
        }

        [TestMethod]
        public void ShouldAcceptASingleGcodeValueWhenEverySlotSavedTheSameOne()
        {
            // filament_vendor is a plain string in the G-code even on a multi-slot printer.
            WritePreset("filament", "My PLA", "filament_vendor = Prusa Polymers\n");

            Assert.AreEqual(string.Empty, Render("; filament_settings_id = \"My PLA\";\"My PLA\"\n; filament_vendor = Prusa Polymers\n"));
        }

        [TestMethod]
        public void ShouldIgnoreBookkeepingKeysThatNeverMeanAChange()
        {
            WritePreset("print", "My Print", "inherits = 0.20mm QUALITY @MK4S\nprint_settings_id = Old Name\npost_process = \"old.exe\"\ncompatible_printers_condition = printer_model==\"MK4S\"\n");

            Assert.AreEqual(string.Empty, Render(Ids + "; inherits = \n; post_process = \"new.exe\"\n; compatible_printers_condition = \n"));
        }

        [TestMethod]
        public void ShouldSkipKeysThatAreNotInTheGcode()
        {
            WritePreset("print", "My Print", "compatible_printers = \nsome_gui_only_key = 1\n");

            Assert.AreEqual(string.Empty, Render(Ids));
        }

        [TestMethod]
        public void ShouldSkipAPresetTypeWhoseFileIsMissingButStillCheckTheOthers()
        {
            // A system preset has no user file; nothing can be said about it, but the printer preset still can be checked.
            WritePreset("printer", "My Printer", "retract_length = 0.8\n");

            var note = Render(Ids + "; fill_density = 25%\n; retract_length = 1.2\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: retract_length = 1.2\n", note);
            Assert.IsTrue(log.Any(l => l.Contains("print preset \"My Print\"")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldSkipFilamentsWhenAnySlotHasNoPresetFile()
        {
            WritePreset("filament", "My PLA", "temperature = 215\n");

            var note = Render("; filament_settings_id = \"My PLA\";\"Prusament PETG\"\n; temperature = 230,240\n");

            Assert.AreEqual(string.Empty, note);
        }

        [TestMethod]
        public void ShouldLookUpAPresetRepeatedAcrossSlotsOnlyOnce()
        {
            // A five-slot printer loaded with one filament names the same preset five times.
            Render("; filament_settings_id = \"My PLA\";\"My PLA\";\"My PLA\";\"My PLA\";\"My PLA\"\n; temperature = 215,215,215,215,215\n");

            Assert.AreEqual(1, log.Count(l => l.Contains("filament preset \"My PLA\"")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldGiveUpOnAPresetFoundUnderTwoConfigRoots()
        {
            var other = Path.Combine(root, "other-root");
            WritePreset("print", "My Print", "fill_density = 15%\n");
            WritePreset("print", "My Print", "fill_density = 15%\n", other);

            Assert.AreEqual(string.Empty, Render(Ids + "; fill_density = 25%\n", root, other));
        }

        [TestMethod]
        public void ShouldRefuseAPresetNameThatIsNotAPlainFileName()
        {
            WritePreset("print", "My Print", "fill_density = 15%\n");

            var note = Render("; print_settings_id = ..\\print\\My Print\n; fill_density = 25%\n");

            Assert.AreEqual(string.Empty, note);
        }

        private void WriteVendorBundle(string bundle, string ini, string? configRoot = null)
        {
            var dir = Path.Combine(configRoot ?? root, "vendor");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, bundle + ".ini"), "# Vendor bundle\nconfig_version = 1.0.0\n\n" + ini);
        }

        [TestMethod]
        public void ShouldResolveASystemPresetThroughItsInheritsChainInTheVendorBundle()
        {
            // Later parents override earlier ones, and the preset's own keys override every parent.
            WriteVendorBundle("Acme", "[print:*common*]\nfill_density = 15%\nperimeters = 2\nlayer_height = 0.2\n\n" +
                "[print:*fast*]\nfill_density = 10%\n\n" +
                "[print:Fast @Acme]\ninherits = *common*; *fast*\nlayer_height = 0.3\n");

            var note = Render("; print_settings_id = Fast @Acme\n; fill_density = 10%\n; perimeters = 3\n; layer_height = 0.3\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: perimeters = 3\n", note);
        }

        [TestMethod]
        public void ShouldPreferTheUsersOwnPresetFileOverAVendorPresetOfTheSameName()
        {
            WriteVendorBundle("Acme", "[print:Fast @Acme]\nfill_density = 15%\n");
            WritePreset("print", "Fast @Acme", "fill_density = 20%\n");

            Assert.AreEqual(string.Empty, Render("; print_settings_id = Fast @Acme\n; fill_density = 20%\n"));
        }

        [TestMethod]
        public void ShouldSkipASystemPresetFoundInMoreThanOneVendorBundle()
        {
            WriteVendorBundle("Acme", "[filament:Generic PLA]\ntemperature = 210\n");
            WriteVendorBundle("Other", "[filament:Generic PLA]\ntemperature = 215\n");

            Assert.AreEqual(string.Empty, Render("; filament_settings_id = \"Generic PLA\"\n; temperature = 220\n"));
            Assert.IsTrue(log.Any(l => l.Contains("filament preset \"Generic PLA\"")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldTreatOneSavedValueAsMatchingEveryExtruderSlotItWasBroadcastTo()
        {
            // A vendor printer preset writes retract_lift once; the G-code repeats it for each of the five extruders.
            WriteVendorBundle("Acme", "[printer:Five Tools]\nretract_lift = 0.2\nextruder_offset = 0x0\nnozzle_diameter = 0.4,0.4,0.4,0.4,0.4\n");

            var same = Render("; printer_settings_id = Five Tools\n; retract_lift = 0.2,0.2,0.2,0.2,0.2\n; extruder_offset = 0x0,0x0,0x0,0x0,0x0\n; nozzle_diameter = 0.4,0.4,0.4,0.4,0.4\n");
            var changed = Render("; printer_settings_id = Five Tools\n; retract_lift = 0.4,0.2,0.2,0.2,0.2\n");

            Assert.AreEqual(string.Empty, same);
            Assert.AreEqual("Profile Changes:\n  Unsaved changes: retract_lift = 0.4,0.2,0.2,0.2,0.2\n", changed);
        }

        [TestMethod]
        public void ShouldTreatAPercentWrittenWithoutItsSignAsTheSameValue()
        {
            // Vendor bundles write some percent options bare (retract_before_wipe = 80); the G-code writes 80%.
            WriteVendorBundle("Acme", "[printer:One Tool]\nretract_before_wipe = 80\n");

            Assert.AreEqual(string.Empty, Render("; printer_settings_id = One Tool\n; retract_before_wipe = 80%\n"));
            Assert.AreEqual("Profile Changes:\n  Unsaved changes: retract_before_wipe = 70%\n", Render("; printer_settings_id = One Tool\n; retract_before_wipe = 70%\n"));
        }

        [TestMethod]
        public void ShouldSkipAVendorBundleItCannotParseAndCarryOn()
        {
            WriteVendorBundle("Broken", "[print:Fast @Acme\nthis is not = = a bundle\n");
            WriteVendorBundle("Acme", "[print:Fast @Acme]\nfill_density = 15%\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: fill_density = 20%\n", Render("; print_settings_id = Fast @Acme\n; fill_density = 20%\n"));
        }

        [TestMethod]
        public void ShouldReportOnlyTheEditedPrintKeysOfARealExportOnStockPresets()
        {
            // A real MK4S MMU3 export where fill density, layer height and top layers were changed in the plater on the
            // stock (system) presets, checked against a pruned copy of the real vendor bundle. binary_gcode = 0 is a
            // genuine printer-preset change: the stock profile exports binary G-code and this file is text.
            var gcode = TestData.Load(Path.Combine("PrusaSlicer", "prusaslicer-2.9.2-mk4s-mmu3-unsaved-print-settings.gcode"));

            var note = Render(gcode, TestData.FullPath(Path.Combine("PrusaSlicer", "config")));

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: fill_density = 20%, layer_height = 0.3, top_solid_layers = 6, binary_gcode = 0\n", note);
        }

        [TestMethod]
        public void ShouldReportEditsAcrossPrintFilamentAndPrinterPresetsOfARealExport()
        {
            // The same print with min_fan_speed changed on the (shared) filament preset and travel_max_lift on extruder 1.
            var gcode = TestData.Load(Path.Combine("PrusaSlicer", "prusaslicer-2.9.2-mk4s-mmu3-unsaved-print-filament-printer.gcode"));

            var note = Render(gcode, TestData.FullPath(Path.Combine("PrusaSlicer", "config")));

            Assert.AreEqual(
                "Profile Changes:\n  Unsaved changes: fill_density = 20%, layer_height = 0.3, top_solid_layers = 6, " +
                "min_fan_speed = 75,75,75,75,75, binary_gcode = 0, travel_max_lift = 1.4,1.5,1.5,1.5,1.5\n",
                note);
        }

        [TestMethod]
        public void ShouldRenderNothingWhenTheConfigRootsCannotBeResolved()
        {
            var settings = GcodeSettings.Parse(Ids, "=");
            var options = new ParseOptions(ParseOptions.InMemory(Ids).OpenFullGcode, log.Add, () => throw new InvalidOperationException("no home directory"));

            var note = PrusaModifiedSettingsPlaceholder.Instance.Render(new ComputedContext(settings, options));

            Assert.AreEqual(string.Empty, note);
            Assert.IsTrue(log.Any(l => l.Contains("no home directory")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldRenderNothingWhenNoPresetIsNamed()
        {
            Assert.AreEqual(string.Empty, Render("; print_settings_id = \n; filament_settings_id = \"\"\n; fill_density = 25%\n"));
        }

        [TestMethod]
        public void ShouldOrderPrintThenFilamentThenPrinterChanges()
        {
            WritePreset("print", "My Print", "perimeters = 2\n");
            WritePreset("filament", "My PLA", "temperature = 215\n");
            WritePreset("printer", "My Printer", "retract_length = 0.8\n");

            var note = Render(Ids + "; retract_length = 1\n; temperature = 220\n; perimeters = 3\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: perimeters = 3, temperature = 220, retract_length = 1\n", note);
        }
    }
}
