using Slic3rPostProcessingUploader.Services.Parsers;
using Slic3rPostProcessingUploader.Services.Parsers.Computed;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers.Computed
{
    /// <summary>
    /// PrusaSlicer G-code carries no list of changed settings, but a user preset's .ini file is a full dump of the
    /// preset, so a key whose G-code value differs from the saved one is an unsaved plater change. The placeholder
    /// checks each preset type (print, every filament slot, printer) against the user's own files and reports what
    /// it can prove; a preset with no readable file (a system preset, another machine) is skipped, never guessed.
    /// </summary>
    [TestClass]
    public class PrusaModifiedSettingsPlaceholderTests
    {
        private string root = null!;
        private readonly List<string> log = [];

        [TestInitialize]
        public void CreateRoot()
        {
            root = Path.Combine(Path.GetTempPath(), "uploader-prusa-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(root);
        }

        [TestCleanup]
        public void DeleteRoot()
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }

        private void WritePreset(string type, string name, string ini, string? configRoot = null)
        {
            var dir = Path.Combine(configRoot ?? root, type);
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, name + ".ini"), "# generated by PrusaSlicer 2.9.2 on 2025-01-01\n" + ini);
        }

        private string Render(string gcode, params string[] roots)
        {
            var settings = GcodeSettings.Parse(gcode, "=");
            var options = new ParseOptions(ParseOptions.InMemory(gcode).OpenFullGcode, log.Add, () => roots.Length == 0 ? [root] : roots);
            return PrusaModifiedSettingsPlaceholder.Instance.Render(new ComputedContext(settings, options));
        }

        private const string Ids = "; print_settings_id = My Print\n; filament_settings_id = \"My PLA\"\n; printer_settings_id = My Printer\n";

        [TestMethod]
        public void ShouldListPrintKeysWhoseGcodeValueDiffersFromTheSavedPreset()
        {
            WritePreset("print", "My Print", "fill_density = 15%\nlayer_height = 0.2\nperimeters = 2\n");

            var note = Render(Ids + "; fill_density = 25%\n; layer_height = 0.2\n; perimeters = 3\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: fill_density = 25%, perimeters = 3\n", note);
        }

        [TestMethod]
        public void ShouldReportASavedValueThatWasClearedInThePlater()
        {
            WritePreset("print", "My Print", "notes = keep me\nfill_density = 15%\n");

            var note = Render(Ids + "; notes = \n; fill_density = 15%\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: notes = \n", note);
        }

        [TestMethod]
        public void ShouldRenderNothingWhenEveryValueMatchesTheSavedPreset()
        {
            WritePreset("print", "My Print", "fill_density = 15%\nlayer_height = 0.2\n");

            Assert.AreEqual(string.Empty, Render(Ids + "; fill_density = 15%\n; layer_height = 0.2\n"));
        }

        [TestMethod]
        public void ShouldCompareFilamentKeysSlotBySlotAgainstEachSlotsPreset()
        {
            WritePreset("filament", "My PLA", "temperature = 215\nfilament_type = PLA\nfilament_notes = \"\"\n");
            WritePreset("filament", "My PETG", "temperature = 240\nfilament_type = PETG\nfilament_notes = \"\"\n");

            var note = Render(
                "; filament_settings_id = \"My PLA\";\"My PETG\"\n" +
                "; temperature = 215,250\n" +
                "; filament_type = PLA;PETG\n" +
                "; filament_notes = \"\";\"\"\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: temperature = 215,250\n", note);
        }

        [TestMethod]
        public void ShouldAcceptASingleGcodeValueWhenEverySlotSavedTheSameOne()
        {
            // filament_vendor is a plain string in the G-code even on a multi-slot printer.
            WritePreset("filament", "My PLA", "filament_vendor = Prusa Polymers\n");

            Assert.AreEqual(string.Empty, Render("; filament_settings_id = \"My PLA\";\"My PLA\"\n; filament_vendor = Prusa Polymers\n"));
        }

        [TestMethod]
        public void ShouldIgnoreBookkeepingKeysThatNeverMeanAChange()
        {
            WritePreset("print", "My Print", "inherits = 0.20mm QUALITY @MK4S\nprint_settings_id = Old Name\npost_process = \"old.exe\"\ncompatible_printers_condition = printer_model==\"MK4S\"\n");

            Assert.AreEqual(string.Empty, Render(Ids + "; inherits = \n; post_process = \"new.exe\"\n; compatible_printers_condition = \n"));
        }

        [TestMethod]
        public void ShouldSkipKeysThatAreNotInTheGcode()
        {
            WritePreset("print", "My Print", "compatible_printers = \nsome_gui_only_key = 1\n");

            Assert.AreEqual(string.Empty, Render(Ids));
        }

        [TestMethod]
        public void ShouldSkipAPresetTypeWhoseFileIsMissingButStillCheckTheOthers()
        {
            // A system preset has no user file; nothing can be said about it, but the printer preset still can be checked.
            WritePreset("printer", "My Printer", "retract_length = 0.8\n");

            var note = Render(Ids + "; fill_density = 25%\n; retract_length = 1.2\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: retract_length = 1.2\n", note);
            Assert.IsTrue(log.Any(l => l.Contains("print preset \"My Print\"")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldSkipFilamentsWhenAnySlotHasNoPresetFile()
        {
            WritePreset("filament", "My PLA", "temperature = 215\n");

            var note = Render("; filament_settings_id = \"My PLA\";\"Prusament PETG\"\n; temperature = 230,240\n");

            Assert.AreEqual(string.Empty, note);
        }

        [TestMethod]
        public void ShouldLookUpAPresetRepeatedAcrossSlotsOnlyOnce()
        {
            // A five-slot printer loaded with one filament names the same preset five times.
            Render("; filament_settings_id = \"My PLA\";\"My PLA\";\"My PLA\";\"My PLA\";\"My PLA\"\n; temperature = 215,215,215,215,215\n");

            Assert.AreEqual(1, log.Count(l => l.Contains("filament preset \"My PLA\"")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldGiveUpOnAPresetFoundUnderTwoConfigRoots()
        {
            var other = Path.Combine(root, "other-root");
            WritePreset("print", "My Print", "fill_density = 15%\n");
            WritePreset("print", "My Print", "fill_density = 15%\n", other);

            Assert.AreEqual(string.Empty, Render(Ids + "; fill_density = 25%\n", root, other));
        }

        [TestMethod]
        public void ShouldRefuseAPresetNameThatIsNotAPlainFileName()
        {
            WritePreset("print", "My Print", "fill_density = 15%\n");

            var note = Render("; print_settings_id = ..\\print\\My Print\n; fill_density = 25%\n");

            Assert.AreEqual(string.Empty, note);
        }

        [TestMethod]
        public void ShouldRenderNothingWhenTheConfigRootsCannotBeResolved()
        {
            var settings = GcodeSettings.Parse(Ids, "=");
            var options = new ParseOptions(ParseOptions.InMemory(Ids).OpenFullGcode, log.Add, () => throw new InvalidOperationException("no home directory"));

            var note = PrusaModifiedSettingsPlaceholder.Instance.Render(new ComputedContext(settings, options));

            Assert.AreEqual(string.Empty, note);
            Assert.IsTrue(log.Any(l => l.Contains("no home directory")), string.Join("\n", log));
        }

        [TestMethod]
        public void ShouldRenderNothingWhenNoPresetIsNamed()
        {
            Assert.AreEqual(string.Empty, Render("; print_settings_id = \n; filament_settings_id = \"\"\n; fill_density = 25%\n"));
        }

        [TestMethod]
        public void ShouldOrderPrintThenFilamentThenPrinterChanges()
        {
            WritePreset("print", "My Print", "perimeters = 2\n");
            WritePreset("filament", "My PLA", "temperature = 215\n");
            WritePreset("printer", "My Printer", "retract_length = 0.8\n");

            var note = Render(Ids + "; retract_length = 1\n; temperature = 220\n; perimeters = 3\n");

            Assert.AreEqual("Profile Changes:\n  Unsaved changes: perimeters = 3, temperature = 220, retract_length = 1\n", note);
        }
    }
}
