namespace Slic3rPostProcessingUploaderUnitTests;

[TestClass]
public sealed class TestDataTests
{
    [TestMethod]
    public void Load_KnownFixture_ReturnsGcodeContents()
    {
        var gcode = TestData.Load(Path.Combine("OrcaSlicer", "orcaslicer-2.2.0-rc-calibration-cube.gcode"));

        StringAssert.Contains(gcode, "generated by OrcaSlicer 2.2.0-rc");
    }

    [TestMethod]
    public void EnumerateFixtures_SlicerFolder_ReturnsRelativePathsInOrdinalOrder()
    {
        var fixtures = TestData.EnumerateFixtures("OrcaSlicer").ToArray();

        CollectionAssert.AreEqual(
            new[]
            {
                Path.Combine("OrcaSlicer", "orcaslicer-2.2.0-rc-calibration-cube-two-filament.gcode"),
                Path.Combine("OrcaSlicer", "orcaslicer-2.2.0-rc-calibration-cube.gcode"),
            },
            fixtures);
    }
}
