using System.IO.Compression;
using System.Text;
using Slic3rPostProcessingUploader.Services;
using Slic3rPostProcessingUploader.Services.Parsers;
using Slic3rPostProcessingUploader.Services.Parsers.PrusaSlicer;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers;

[TestClass]
public sealed class BinaryGcodeTests
{
    private const ushort FileMetadata = 0;
    private const ushort GCode = 1;
    private const ushort SlicerMetadata = 2;
    private const ushort PrinterMetadata = 3;
    private const ushort PrintMetadata = 4;
    private const ushort Thumbnail = 5;

    private const ushort NoCompression = 0;
    private const ushort Deflate = 1;
    private const ushort Heatshrink12 = 3;

    private static readonly byte[] PngHeader = [0x89, (byte)'P', (byte)'N', (byte)'G', 0x0D, 0x0A, 0x1A, 0x0A, 1, 2, 3];

    /// <summary>
    /// Builds a libbgcode v1 file from blocks. Each block is (type, compression, parameters, uncompressed payload).
    /// </summary>
    private static byte[] Build(bool withChecksum, params (ushort type, ushort compression, byte[] parameters, byte[] payload)[] blocks)
    {
        using var file = new MemoryStream();
        using var writer = new BinaryWriter(file);
        writer.Write("GCDE"u8);
        writer.Write(1u);
        writer.Write((ushort)(withChecksum ? 1 : 0));

        foreach (var (type, compression, parameters, payload) in blocks)
        {
            var data = compression == Deflate ? ZlibCompress(payload) : payload;

            using var block = new MemoryStream();
            using var blockWriter = new BinaryWriter(block);
            blockWriter.Write(type);
            blockWriter.Write(compression);
            blockWriter.Write((uint)payload.Length);
            if (compression != NoCompression)
            {
                blockWriter.Write((uint)data.Length);
            }
            blockWriter.Write(parameters);
            blockWriter.Write(data);
            blockWriter.Flush();

            var bytes = block.ToArray();
            writer.Write(bytes);
            if (withChecksum)
            {
                writer.Write(BinaryGcode.Crc32(bytes));
            }
        }

        writer.Flush();
        return file.ToArray();
    }

    private static byte[] ZlibCompress(byte[] payload)
    {
        using var output = new MemoryStream();
        using (var zlib = new ZLibStream(output, CompressionLevel.Optimal, leaveOpen: true))
        {
            zlib.Write(payload);
        }
        return output.ToArray();
    }

    private static (ushort, ushort, byte[], byte[]) Ini(ushort type, string text, ushort compression = NoCompression) =>
        (type, compression, [0, 0], Encoding.UTF8.GetBytes(text));

    private static (ushort, ushort, byte[], byte[]) Image(ushort format, ushort width, ushort height, byte[] bytes)
    {
        var parameters = new byte[6];
        BitConverter.TryWriteBytes(parameters.AsSpan(0), format);
        BitConverter.TryWriteBytes(parameters.AsSpan(2), width);
        BitConverter.TryWriteBytes(parameters.AsSpan(4), height);
        return (Thumbnail, NoCompression, parameters, bytes);
    }

    private static string Decode(byte[] file) => BinaryGcode.Decode(new MemoryStream(file));

    [TestMethod]
    public void Crc32_MatchesIeeeCheckValue()
    {
        Assert.AreEqual(0xCBF43926u, BinaryGcode.Crc32("123456789"u8));
    }

    [TestMethod]
    public void IsBinaryGcode_RecognisesMagicOnly()
    {
        Assert.IsTrue(BinaryGcode.IsBinaryGcode("GCDE\0\0\0\0"u8));
        Assert.IsFalse(BinaryGcode.IsBinaryGcode("; generated by PrusaSlicer"u8));
        Assert.IsFalse(BinaryGcode.IsBinaryGcode("GC"u8));
        Assert.IsFalse(BinaryGcode.IsBinaryGcode(ReadOnlySpan<byte>.Empty));
    }

    [TestMethod]
    public void ShouldEmitProducerLineThatPrusaParserRecognises()
    {
        var file = Build(true, Ini(FileMetadata, "Producer=PrusaSlicer 2.9.2\nProduced on=2026-09-13 at 17:40:11 UTC\n"));

        var text = Decode(file);

        StringAssert.Contains(text, "; generated by PrusaSlicer 2.9.2 on 2026-09-13 at 17:40:11 UTC");
        Assert.IsTrue(PrusaParser.IsPrusaSlicer(text));
        Assert.AreEqual("2.9.2", new PrusaParser("").ParseGcode(text).CuraVersion);
    }

    [TestMethod]
    public void ShouldRewriteUncompressedMetadataAsCommentSettings()
    {
        var file = Build(true, Ini(PrinterMetadata, "printer_model=MK4SMMU3\nfilament used [mm]=2106.08, 0.00\nobjects_info={\"a\":\"b=c\"}\n"));

        var text = Decode(file);

        StringAssert.Contains(text, "; printer_model = MK4SMMU3\n");
        StringAssert.Contains(text, "; filament used [mm] = 2106.08, 0.00\n");
        // Only the first '=' separates key from value.
        StringAssert.Contains(text, "; objects_info = {\"a\":\"b=c\"}\n");
    }

    [TestMethod]
    public void ShouldInflateDeflateCompressedMetadata()
    {
        var file = Build(true, Ini(PrintMetadata, "filament used [g]=6.28, 0.00\nestimated printing time (normal mode)=16m 47s\n", Deflate));

        var text = Decode(file);

        StringAssert.Contains(text, "; filament used [g] = 6.28, 0.00\n");
        StringAssert.Contains(text, "; estimated printing time (normal mode) = 16m 47s\n");
    }

    [TestMethod]
    public void ShouldWrapSlicerMetadataInConfigMarkers()
    {
        var file = Build(true, Ini(SlicerMetadata, "layer_height=0.2\nfilament_colour=#E72F1D;#1F77B4\n", Deflate));

        var text = Decode(file);

        var configStart = text.IndexOf("; prusaslicer_config = begin\n", StringComparison.Ordinal);
        var configEnd = text.IndexOf("; prusaslicer_config = end", StringComparison.Ordinal);
        var setting = text.IndexOf("; layer_height = 0.2\n", StringComparison.Ordinal);
        Assert.IsTrue(configStart >= 0 && setting > configStart && configEnd > setting, text);
    }

    [TestMethod]
    public void ShouldEmitPngThumbnailAsBase64BlockAndSkipQoi()
    {
        var file = Build(true,
            Image(format: 2, 16, 16, [1, 2, 3, 4]),
            Image(format: 0, 640, 480, PngHeader));

        var text = Decode(file);

        StringAssert.Contains(text, $"; thumbnail begin 640x480 {PngHeader.Length}\n");
        StringAssert.Contains(text, "; " + Convert.ToBase64String(PngHeader) + "\n");
        StringAssert.Contains(text, "; thumbnail end\n");
        Assert.IsFalse(text.Contains("16x16"), "QOI thumbnails cannot be rendered by browsers and must be skipped.");

        var snapshot = new PrusaParser("").ParseGcode(text).settings.Snapshot;
        Assert.AreEqual(Convert.ToBase64String(PngHeader), snapshot);
    }

    [TestMethod]
    public void ShouldWrapLongBase64Lines()
    {
        var bytes = Enumerable.Range(0, 300).Select(i => (byte)i).ToArray();
        var file = Build(true, Image(format: 1, 100, 100, bytes));

        var text = Decode(file);

        var lines = text.Split('\n').Where(l => l.StartsWith("; ") && l.Length > 2 && !l.StartsWith("; thumbnail")).ToList();
        Assert.IsTrue(lines.Count > 1);
        Assert.IsTrue(lines.All(l => l.Length <= 80), "Base64 should be wrapped like the slicers do.");
        Assert.AreEqual(Convert.ToBase64String(bytes), string.Concat(lines.Select(l => l[2..])));
    }

    [TestMethod]
    public void ShouldSkipGcodeBlocksWithoutDecodingThem()
    {
        var garbage = Enumerable.Repeat((byte)0xFF, 1000).ToArray();
        var file = Build(true,
            Ini(FileMetadata, "Producer=PrusaSlicer 2.9.2\nProduced on=now\n"),
            (GCode, Heatshrink12, [2, 0], garbage),
            (GCode, Heatshrink12, [2, 0], garbage),
            Ini(PrintMetadata, "total filament used [g]=6.28\n", Deflate));

        var text = Decode(file);

        StringAssert.Contains(text, "; total filament used [g] = 6.28\n");
        Assert.IsFalse(text.Contains('�'), "G-code payload must not leak into the output.");
    }

    [TestMethod]
    public void ShouldParseFileWithoutChecksums()
    {
        var file = Build(false,
            Ini(FileMetadata, "Producer=PrusaSlicer 2.9.2\nProduced on=now\n"),
            Ini(PrintMetadata, "total filament used [g]=6.28\n", Deflate));

        var text = Decode(file);

        StringAssert.Contains(text, "; total filament used [g] = 6.28\n");
    }

    [TestMethod]
    public void ShouldRejectCorruptBlock()
    {
        var file = Build(true, Ini(PrinterMetadata, "printer_model=MK4S\n"));
        file[^1] ^= 0xFF; // flip a checksum byte

        var ex = Assert.ThrowsException<UserFacingException>(() => Decode(file));

        StringAssert.Contains(ex.Message, "corrupt or truncated");
    }

    [TestMethod]
    public void ShouldRejectTruncatedFile()
    {
        var file = Build(true, Ini(PrinterMetadata, "printer_model=MK4S\n"));

        var ex = Assert.ThrowsException<UserFacingException>(() => Decode(file[..^6]));

        StringAssert.Contains(ex.Message, "corrupt or truncated");
    }

    [TestMethod]
    public void ShouldRejectUnsupportedVersion()
    {
        var file = Build(true, Ini(PrinterMetadata, "printer_model=MK4S\n"));
        file[4] = 2;

        var ex = Assert.ThrowsException<UserFacingException>(() => Decode(file));

        StringAssert.Contains(ex.Message, "version 2");
    }

    [TestMethod]
    public void ShouldRejectHeatshrinkCompressedMetadata()
    {
        var file = Build(true, (PrinterMetadata, Heatshrink12, [0, 0], [1, 2, 3]));

        var ex = Assert.ThrowsException<UserFacingException>(() => Decode(file));

        StringAssert.Contains(ex.Message, "Heatshrink");
        StringAssert.Contains(ex.Message, "printer metadata");
    }

    [TestMethod]
    public void ShouldRejectNonBinaryInput()
    {
        var ex = Assert.ThrowsException<UserFacingException>(() => Decode("; generated by PrusaSlicer\n"u8.ToArray()));

        StringAssert.Contains(ex.Message, "not a binary G-code");
    }

    [TestMethod]
    public void ShouldDecodeRealGuiExportEndToEnd()
    {
        var text = BinaryGcode.ReadFromFile(TestData.FullPath(Path.Combine("PrusaSlicer", "prusaslicer-2.9.2-mk4smmu3-shape-box.bgcode")));

        var result = new PrusaParser("").ParseGcode(text);

        Assert.AreEqual("PrusaSlicer", result.Slicer);
        Assert.AreEqual("2.9.2", result.CuraVersion);
        Assert.AreEqual(1007, result.settings.estimated_print_time_seconds);
        Assert.AreEqual(1, result.settings.filamentUsage!.Count);
        Assert.AreEqual(2.106, result.settings.filamentUsage[0].EstimatedLengthInM);
        StringAssert.StartsWith(result.settings.filamentUsage[0].Notes, "Slot 1 · ");
        StringAssert.EndsWith(result.settings.filamentUsage[0].Notes, " · PLA");
        // The 640x480 PNG block, not one of the QOI ones.
        StringAssert.StartsWith(result.settings.Snapshot, "iVBORw0KGgo");
    }

    [TestMethod]
    public void ShouldParseIdenticallyToTheAsciiExportOfTheSameSlice()
    {
        // Both fixtures come from the same PrusaSlicer 2.9.2 CLI run, once as .gcode and once as .bgcode.
        var ascii = TestData.Load(Path.Combine("PrusaSlicer", "prusaslicer-2.9.2-mk4s-mmu3-two-slots-pla-petg.gcode"));
        var binary = TestData.Load(Path.Combine("PrusaSlicer", "prusaslicer-2.9.2-mk4s-mmu3-two-slots-pla-petg-binary.bgcode"));

        var fromAscii = new PrusaParser("").ParseGcode(ascii);
        var fromBinary = new PrusaParser("").ParseGcode(binary);

        Assert.AreEqual(fromAscii.ToJSON(), fromBinary.ToJSON());
    }
}
