using System.Text;
using System.Text.RegularExpressions;
using Slic3rPostProcessingUploader.Services;
using Slic3rPostProcessingUploader.Services.Parsers;
using Slic3rPostProcessingUploader.Services.Parsers.Computed;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers
{
    /// <summary>
    /// Computed placeholders are template keys whose value comes from code rather than a "; key = value" line.
    /// These tests cover the plumbing in <see cref="GcodeParserBase"/>: when a provider runs, how its (possibly
    /// multi-line) value is laid out, and how it interacts with the settings index and the factory's scoring.
    /// </summary>
    [TestClass]
    public partial class ComputedPlaceholderTests
    {
        private const string Gcode = "; generated by TestSlicer 1.0 on today\n; layer_height = 0.2\n; models = from-gcode\n";

        private sealed partial class TestParser(string template, params ComputedPlaceholder[] computed) : GcodeParserBase(template)
        {
            protected override string SlicerName => "TestSlicer";
            [GeneratedRegex("generated by TestSlicer (.+) on")]
            private static partial Regex VersionRegex();
            protected override Regex SlicerVersionRegex => VersionRegex();
            protected override INoteTemplate CreateDefaultTemplate() => throw new NotSupportedException();
            protected override IReadOnlyList<ComputedPlaceholder> ComputedPlaceholders => computed;
        }

        private static ComputedPlaceholder Constant(string key, string value) => new(key, _ => value);

        private static ParseOptions ThrowingOpener() =>
            new(() => throw new InvalidOperationException("full gcode must not be opened"), _ => { });

        [TestMethod]
        public void ShouldNotRunAProviderTheTemplateDoesNotReference()
        {
            var parser = new TestParser("Layer: {{layer_height}}", new ComputedPlaceholder("models", _ => throw new Exception("must not run")));

            var result = parser.ParseGcode(Gcode, ThrowingOpener());

            Assert.AreEqual("Layer: 0.2", result.settings.note);
        }

        [TestMethod]
        public void ShouldRunAProviderTheTemplateReferences()
        {
            var parser = new TestParser("Models: {{models}}", Constant("models", "one"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models: one", result.settings.note);
        }

        [TestMethod]
        public void ShouldOverrideASameNamedSettingsLine()
        {
            var parser = new TestParser("{{models}}", Constant("models", "computed"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("computed", result.settings.note);
        }

        [TestMethod]
        public void ShouldMatchProviderKeysCaseInsensitively()
        {
            var parser = new TestParser("{{Models}}", Constant("models", "computed"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("computed", result.settings.note);
        }

        [TestMethod]
        public void ShouldGiveProvidersTheParsedSettings()
        {
            var parser = new TestParser("{{echo}}", new ComputedPlaceholder("echo", c => "lh=" + c.Settings.Get("layer_height")));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("lh=0.2", result.settings.note);
        }

        [TestMethod]
        public void ShouldGiveProvidersTheFullGcodeStream()
        {
            var parser = new TestParser("{{first}}", new ComputedPlaceholder("first", c =>
            {
                using var reader = new StreamReader(c.OpenFullGcode(), Encoding.UTF8);
                return reader.ReadLine()!;
            }));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("; generated by TestSlicer 1.0 on today", result.settings.note);
        }

        [TestMethod]
        public void ShouldIndentEveryLineOfAStandaloneValueLikeThePlaceholderLine()
        {
            var parser = new TestParser("Models:\n  {{models}}\nEnd", Constant("models", "a\nb"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models:\n  a\n  b\nEnd", result.settings.note);
        }

        [TestMethod]
        public void ShouldKeepCrlfSeparatorsWhenTheTemplateUsesThem()
        {
            var parser = new TestParser("Models:\r\n  {{models}}\r\nEnd", Constant("models", "a\nb"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models:\r\n  a\r\n  b\r\nEnd", result.settings.note);
        }

        [TestMethod]
        public void ShouldRemoveTheLineWhenAStandaloneValueIsEmpty()
        {
            var parser = new TestParser("Models:\n  {{models}}\nEnd", Constant("models", ""));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models:\nEnd", result.settings.note);
        }

        [TestMethod]
        public void ShouldHandleAStandalonePlaceholderAtTheEndOfTheTemplate()
        {
            var parser = new TestParser("Models:\n  {{models}}", Constant("models", "a\nb"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models:\n  a\n  b", result.settings.note);
        }

        [TestMethod]
        public void ShouldRemoveATrailingStandaloneLineWhenTheValueIsEmpty()
        {
            var parser = new TestParser("Models:\n  {{models}}", Constant("models", ""));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models:\n", result.settings.note);
        }

        [TestMethod]
        public void ShouldSubstituteInlinePlaceholdersVerbatim()
        {
            var parser = new TestParser("Models: {{models}} end", Constant("models", "a\nb"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models: a\nb end", result.settings.note);
        }

        [TestMethod]
        public void ShouldApplyTheStandaloneRuleToOrdinarySettingsToo()
        {
            var parser = new TestParser("Layer:\n  {{layer_height}}\n  {{missing_key}}\nEnd");

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Layer:\n  0.2\nEnd", result.settings.note);
        }

        [TestMethod]
        public void ShouldNotCountComputedKeysWhenScoringTemplateMatches()
        {
            var parser = new TestParser("{{layer_height}} {{models}} {{nothing}}", Constant("models", "x"));

            var (numPlaceholders, numMatches) = parser.CountTemplateMatches(Gcode);

            Assert.AreEqual(2, numPlaceholders);
            Assert.AreEqual(1, numMatches);
        }

        [TestMethod]
        public void InMemoryOptionsShouldExposeTheGcodeAsAUtf8Stream()
        {
            var options = ParseOptions.InMemory("; héllo\n");

            using var reader = new StreamReader(options.OpenFullGcode(), Encoding.UTF8);
            Assert.AreEqual("; héllo", reader.ReadLine());
        }

        [TestMethod]
        public void ShouldNotTreatPlaceholderSyntaxInsideAStandaloneValueAsATemplate()
        {
            var parser = new TestParser("Models:\n  {{models}}\n", Constant("models", "name {{layer_height}}"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models:\n  name {{layer_height}}\n", result.settings.note);
        }

        [TestMethod]
        public void ShouldNotTreatPlaceholderSyntaxInsideAnInlineValueAsATemplate()
        {
            var parser = new TestParser("Models: {{models}}", Constant("models", "name {{layer_height}}"));

            var result = parser.ParseGcode(Gcode);

            Assert.AreEqual("Models: name {{layer_height}}", result.settings.note);
        }
    }
}
