using Slic3rPostProcessingUploader.Services.Parsers.OrcaSlicer;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers
{
    [TestClass]
    public class FilamentUsageNotesTests
    {
        [TestMethod]
        public void ShouldDescribeEachUsedSlotWithColorAndType()
        {
            var gcode = """
                ; generated by OrcaSlicer 2.3.0
                ; filament used [mm] = 78394.37, 31200.24, 0.00, 7257.90, 0.00
                ; filament_colour = #E72F1D;#080A0D;#FFFFFF;#0078BF;#A6A9AA
                ; filament_type = PLA;PLA;PLA;PETG;PLA
                """;

            var result = new OrcaParser("").ParseGcode(gcode);

            var notes = result.settings.filamentUsage!.Select(f => f.Notes).ToList();
            CollectionAssert.AreEqual(new[]
            {
                "Slot 1 · Red (#E72F1D) · PLA",
                "Slot 2 · Black (#080A0D) · PLA",
                "Slot 4 · Blue (#0078BF) · PETG",
            }, notes);
        }

        [TestMethod]
        public void ShouldFallBackToSlotNumberWhenColorAndTypeAreMissing()
        {
            var gcode = """
                ; generated by OrcaSlicer 2.3.0
                ; filament used [mm] = 1519.88, 1874.36
                """;

            var result = new OrcaParser("").ParseGcode(gcode);

            var notes = result.settings.filamentUsage!.Select(f => f.Notes).ToList();
            CollectionAssert.AreEqual(new[] { "Slot 1", "Slot 2" }, notes);
        }

        [TestMethod]
        public void ShouldShowRawHexWhenColorIsNotRecognised()
        {
            var gcode = """
                ; generated by OrcaSlicer 2.3.0
                ; filament used [mm] = 1519.88
                ; filament_colour = not-a-colour
                ; filament_type = PLA
                """;

            var result = new OrcaParser("").ParseGcode(gcode);

            Assert.AreEqual("Slot 1 · not-a-colour · PLA", result.settings.filamentUsage![0].Notes);
        }

        [TestMethod]
        public void ShouldTreatQuotedEmptyColourAsMissing()
        {
            // PrusaSlicer 3.0 writes an unset colour as a pair of quotes.
            var gcode = """
                ; generated by OrcaSlicer 2.3.0
                ; filament used [mm] = 1519.88
                ; filament_colour = ""
                ; filament_type = PLA
                """;

            var result = new OrcaParser("").ParseGcode(gcode);

            Assert.AreEqual("Slot 1 · PLA", result.settings.filamentUsage![0].Notes);
        }

        [TestMethod]
        public void ShouldNotThrowWhenColorListIsShorterThanUsageList()
        {
            var gcode = """
                ; generated by OrcaSlicer 2.3.0
                ; filament used [mm] = 1519.88, 1874.36
                ; filament_colour = #E72F1D
                ; filament_type = PLA
                """;

            var result = new OrcaParser("").ParseGcode(gcode);

            var notes = result.settings.filamentUsage!.Select(f => f.Notes).ToList();
            CollectionAssert.AreEqual(new[] { "Slot 1 · Red (#E72F1D) · PLA", "Slot 2" }, notes);
        }
    }
}
