using Slic3rPostProcessingUploader.Services.Parsers.OrcaSlicer;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers
{
    /// <summary>
    /// Thumbnail selection lives in GcodeParserBase and is shared by every slicer parser,
    /// so these tests exercise it through one concrete parser (OrcaParser).
    /// </summary>
    [TestClass]
    public class GcodeParserBaseSnapshotTests
    {
        private static string Thumbnail(string header, string payload) => $"""
            ; THUMBNAIL_BLOCK_START
            ; {header}
            ; {payload}
            ; thumbnail end
            ; THUMBNAIL_BLOCK_END

            """;

        // Minimal settings so the filament estimate does not throw on a header-only fixture.
        private const string FilamentHeader = """
            ; filament_diameter = 1.75
            ; filament used [mm] = 0
            ; filament_type = PLA

            """;

        private static string? Parse(string gcode) => new OrcaParser("").ParseGcode(FilamentHeader + gcode).settings.Snapshot;

        [TestMethod]
        public void ShouldReturnNullWhenThereIsNoThumbnail()
        {
            Assert.IsNull(Parse("; generated by OrcaSlicer 2.2.0\n"));
        }

        [TestMethod]
        public void ShouldReturnTheOnlyThumbnailWhenThereIsOne()
        {
            var gcode = Thumbnail("thumbnail begin 48x48 100", "SMALL");

            Assert.AreEqual("SMALL", Parse(gcode));
        }

        [TestMethod]
        public void ShouldPickTheLargerThumbnailWhenTheSmallerOneComesFirst()
        {
            var gcode = Thumbnail("thumbnail begin 48x48 100", "SMALL")
                      + Thumbnail("thumbnail begin 300x300 100", "LARGE");

            Assert.AreEqual("LARGE", Parse(gcode));
        }

        [TestMethod]
        public void ShouldPickTheLargerThumbnailWhenTheLargerOneComesFirst()
        {
            var gcode = Thumbnail("thumbnail begin 300x300 100", "LARGE")
                      + Thumbnail("thumbnail begin 48x48 100", "SMALL");

            Assert.AreEqual("LARGE", Parse(gcode));
        }

        [TestMethod]
        public void ShouldIgnoreThumbnailsLargerThan720pWhenASmallerOneExists()
        {
            var gcode = Thumbnail("thumbnail begin 300x300 100", "MEDIUM")
                      + Thumbnail("thumbnail begin 1920x1080 100", "HUGE");

            Assert.AreEqual("MEDIUM", Parse(gcode));
        }

        [TestMethod]
        public void ShouldAllowExactly1280x720()
        {
            var gcode = Thumbnail("thumbnail begin 300x300 100", "MEDIUM")
                      + Thumbnail("thumbnail begin 1280x720 100", "HD");

            Assert.AreEqual("HD", Parse(gcode));
        }

        [TestMethod]
        public void ShouldRejectThumbnailsThatExceedOnlyOneDimension()
        {
            var gcode = Thumbnail("thumbnail begin 300x300 100", "MEDIUM")
                      + Thumbnail("thumbnail begin 800x800 100", "TOO_TALL");

            Assert.AreEqual("MEDIUM", Parse(gcode));
        }

        [TestMethod]
        public void ShouldFallBackToTheSmallestThumbnailWhenAllExceed720p()
        {
            var gcode = Thumbnail("thumbnail begin 3840x2160 100", "4K")
                      + Thumbnail("thumbnail begin 1920x1080 100", "FHD");

            Assert.AreEqual("FHD", Parse(gcode));
        }

        [TestMethod]
        public void ShouldHandleHeadersWithTrailingWords()
        {
            var gcode = Thumbnail("thumbnail begin 230x110 100", "SMALL")
                      + Thumbnail("thumbnail begin 512x512 100 top", "LARGE");

            Assert.AreEqual("LARGE", Parse(gcode));
        }

        [TestMethod]
        public void ShouldIncludeJpgThumbnails()
        {
            var gcode = Thumbnail("thumbnail begin 48x48 100", "SMALL_PNG")
                      + Thumbnail("thumbnail_JPG begin 640x480 100", "LARGE_JPG");

            Assert.AreEqual("LARGE_JPG", Parse(gcode));
        }

        [TestMethod]
        public void ShouldIgnoreQoiThumbnails()
        {
            var gcode = Thumbnail("thumbnail begin 48x48 100", "SMALL_PNG")
                      + Thumbnail("thumbnail_QOI begin 640x480 100", "LARGE_QOI");

            Assert.AreEqual("SMALL_PNG", Parse(gcode));
        }

        [TestMethod]
        public void ShouldJoinMultiLinePayloadsAndStripCommentPrefixes()
        {
            var gcode = """
                ; thumbnail begin 48x48 100
                ; AAAA
                ; BBBB
                ; thumbnail end

                """;

            Assert.AreEqual("AAAABBBB", Parse(gcode));
        }
    }
}
