using System.Text;
using Slic3rPostProcessingUploader.Services.Parsers;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers
{
    [TestClass]
    public class GcodeWindowTests
    {
        [TestMethod]
        public void ShouldReturnTheSameStringWhenItFitsInTheWindow()
        {
            var gcode = "; small file\n";

            Assert.AreSame(gcode, GcodeWindow.Trim(gcode));
        }

        [TestMethod]
        public void ShouldKeepTheHeadAndTailAndDropTheMiddleWhenTheStringIsLarge()
        {
            var head = "; HEAD\n";
            var tail = "; TAIL\n";
            var middle = new string('G', GcodeWindow.WindowSize * 3);

            var result = GcodeWindow.Trim(head + middle + tail);

            Assert.IsTrue(result.StartsWith(head));
            Assert.IsTrue(result.EndsWith(tail));
            Assert.IsTrue(result.Length <= GcodeWindow.WindowSize * 2 + 1);
        }

        [TestMethod]
        public void ShouldSeparateHeadAndTailWithANewlineSoLinesAreNotSpliced()
        {
            var head = new string('H', GcodeWindow.WindowSize);
            var tail = new string('T', GcodeWindow.WindowSize);

            var result = GcodeWindow.Trim(head + "MIDDLE" + tail);

            Assert.AreEqual(head + "\n" + tail, result);
        }

        [TestMethod]
        public void ShouldReadTheWholeFileWhenItIsSmall()
        {
            var path = Path.GetTempFileName();
            try
            {
                File.WriteAllText(path, "; generated by OrcaSlicer\n; layer_height = 0.2\n");

                Assert.AreEqual("; generated by OrcaSlicer\n; layer_height = 0.2\n", GcodeWindow.ReadFromFile(path));
            }
            finally
            {
                File.Delete(path);
            }
        }

        [TestMethod]
        public void ShouldStripTheByteOrderMarkWhenReadingAFile()
        {
            var path = Path.GetTempFileName();
            try
            {
                File.WriteAllText(path, "; generated by OrcaSlicer\n", new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));

                Assert.AreEqual("; generated by OrcaSlicer\n", GcodeWindow.ReadFromFile(path));
            }
            finally
            {
                File.Delete(path);
            }
        }

        [TestMethod]
        public void ShouldReadOnlyTheHeadAndTailWhenARealFixtureIsLarge()
        {
            var fixture = TestData.Load(Path.Combine("AnycubicSlicerNext", "anycubicslicernext-1.3.2-calibration-cube-two-filament.gcode"));
            var expandedFixture = string.Concat(fixture, fixture, fixture, fixture);
            var path = Path.GetTempFileName();
            try
            {
                File.WriteAllText(path, expandedFixture, new UTF8Encoding(false));

                var result = GcodeWindow.ReadFromFile(path);

                StringAssert.StartsWith(result, fixture[..100]);
                StringAssert.EndsWith(result, fixture[^100..]);
                Assert.IsTrue(result.Length <= GcodeWindow.WindowSize * 2 + 1);
            }
            finally
            {
                File.Delete(path);
            }
        }

        [TestMethod]
        public void ShouldNotThrowWhenTheTailStartsInTheMiddleOfAMultiByteCharacter()
        {
            var path = Path.GetTempFileName();
            try
            {
                using (var writer = new StreamWriter(path, false, new UTF8Encoding(false)))
                {
                    writer.Write("; HEAD\n");
                    // Fill with 3-byte characters so the tail boundary lands mid-character.
                    for (long written = 0; written < GcodeWindow.WindowSize * 3L; written += 1)
                    {
                        writer.Write('\u20ac');
                    }
                    writer.Write("\n; TAIL\n");
                }

                var result = GcodeWindow.ReadFromFile(path);

                Assert.IsTrue(result.EndsWith("\n; TAIL\n"));
            }
            finally
            {
                File.Delete(path);
            }
        }
    }
}
