using Slic3rPostProcessingUploader.Services;
using Slic3rPostProcessingUploader.Services.Parsers;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers
{
    [TestClass]
    public class ParserFactoryTests
    {
        private StringWriter _screen = null!;
        private ConsoleOutput _output = null!;
        private TelemetryService _telemetry = null!;

        [TestInitialize]
        public void Setup()
        {
            _screen = new StringWriter();
            _output = new ConsoleOutput(_screen, null, verbose: false, unicode: true, useColor: false);
            _telemetry = new TelemetryService(disableTelemetry: true);
        }

        [TestCleanup]
        public void Cleanup() => _telemetry.Dispose();

        [TestMethod]
        public void GetParser_RecognizedSlicer_PrintsNothing()
        {
            ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, "; generated by OrcaSlicer 2.3.0\n");

            Assert.AreEqual(string.Empty, _screen.ToString());
        }

        [TestMethod]
        public void GetParser_UnrecognizedSlicer_WarnsAboutBestMatchFallback()
        {
            ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, "; some unknown slicer\n; layer_height = 0.2\n");

            StringAssert.StartsWith(_screen.ToString(), "  ! Slicer not recognized");
        }
    }
}
