using Slic3rPostProcessingUploader.Services;
using Slic3rPostProcessingUploader.Services.Parsers;
using Slic3rPostProcessingUploader.Services.Parsers.AnycubicSlicerNext;
using Slic3rPostProcessingUploader.Services.Parsers.BambuStudio;
using Slic3rPostProcessingUploader.Services.Parsers.FLSunSlicer;
using Slic3rPostProcessingUploader.Services.Parsers.OrcaSlicer;
using Slic3rPostProcessingUploader.Services.Parsers.PrusaSlicer;

namespace Slic3rPostProcessingUploaderUnitTests.Services.Parsers
{
    [TestClass]
    public class ParserFactoryTests
    {
        private StringWriter _screen = null!;
        private ConsoleOutput _output = null!;
        private TelemetryService _telemetry = null!;

        [TestInitialize]
        public void Setup()
        {
            _screen = new StringWriter();
            _output = new ConsoleOutput(_screen, null, verbose: false, unicode: true, useColor: false);
            _telemetry = new TelemetryService(disableTelemetry: true);
        }

        [TestCleanup]
        public void Cleanup() => _telemetry.Dispose();

        [TestMethod]
        public void GetParser_RecognizedSlicer_PrintsNothing()
        {
            ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, "; generated by OrcaSlicer 2.3.0\n");

            Assert.AreEqual(string.Empty, _screen.ToString());
        }

        [TestMethod]
        public void GetParser_UnrecognizedSlicer_WarnsAboutBestMatchFallback()
        {
            ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, "; some unknown slicer\n; layer_height = 0.2\n");

            StringAssert.StartsWith(_screen.ToString(), "  ! Slicer not recognized");
        }

        [TestMethod]
        [DataRow("; generated by OrcaSlicer 2.3.0\n", typeof(OrcaParser))]
        [DataRow("; generated by PrusaSlicer 2.9.0 on 2025-01-01\n", typeof(PrusaParser))]
        [DataRow("; generated by FlsunSlicer 1.0.0\n", typeof(FLSunParser))]
        [DataRow("; BambuStudio 1.10.0\n", typeof(BambuStudioParser))]
        [DataRow("; generated by AnycubicSlicerNext 1.0.0\n", typeof(AnycubicSlicerNextParser))]
        public void GetParser_SlicerMarker_SelectsMatchingParser(string gcode, Type expectedParser)
        {
            var parser = ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, gcode);

            Assert.AreEqual(expectedParser, parser.GetType());
            Assert.AreEqual(string.Empty, _screen.ToString());
        }

        [TestMethod]
        public void GetParser_NoMarkerWithPrusaOnlyKeys_FallsBackToPrusaParser()
        {
            var gcode = "; some unknown slicer\n; perimeters = 3\n; fill_density = 15%\n; perimeter_generator = arachne\n; top_solid_min_thickness = 0.7\n";

            var parser = ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, gcode);

            Assert.IsInstanceOfType<PrusaParser>(parser);
        }

        [TestMethod]
        public void GetParser_EmptyGcode_FallsBackToOrcaParser()
        {
            var parser = ParserFactory.GetParser(new ArgumentParser(["--default"]), _telemetry, _output, string.Empty);

            Assert.IsInstanceOfType<OrcaParser>(parser);
        }
    }
}
