using System.Text.RegularExpressions;

namespace Slic3rPostProcessingUploader.Services.Parsers.AnycubicSlicerNext
{
    internal partial class AnycubicSlicerNextParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "AnycubicSlicerNext";
        [GeneratedRegex(@"generated by AnycubicSlicerNext (.+) on", RegexOptions.IgnoreCase | RegexOptions.Multiline)]
        private static partial Regex VersionRegex();
        protected override Regex SlicerVersionRegex => VersionRegex();
        protected override INoteTemplate CreateDefaultTemplate() => EmbeddedNoteTemplate.Default("AnycubicSlicerNext");
        protected override bool SupportsMultiFilament => true;

        public static bool IsAnycubicSlicerNext(string gcode)
        {
            return gcode.Contains("generated by AnycubicSlicerNext", StringComparison.Ordinal);
        }
    }
}
