using System.Text.RegularExpressions;

namespace Slic3rPostProcessingUploader.Services.Parsers.PrusaSlicer
{
    internal partial class PrusaParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "PrusaSlicer";
        [GeneratedRegex(@"generated by PrusaSlicer (.+) on", RegexOptions.IgnoreCase | RegexOptions.Multiline)]
        private static partial Regex VersionRegex();
        protected override Regex SlicerVersionRegex => VersionRegex();
        // MMU and XL exports write one "filament used" value per extruder slot, in the same shape OrcaSlicer uses.
        protected override bool SupportsMultiFilament => true;
        protected override INoteTemplate CreateDefaultTemplate() => EmbeddedNoteTemplate.Default("PrusaSlicer");

        public static bool IsPrusaSlicer(string gcode)
        {
            return gcode.Contains("generated by PrusaSlicer", StringComparison.Ordinal);
        }
    }
}
