; generated by PrusaSlicer 3.0.0-alpha11 on 2026-09-13 at 12:12:32 UTC

;

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.40mm
; first layer extrusion width = 0.50mm

M73 P0 R26
M73 Q0 S26
M201 X4000 Y4000 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X400 Y400 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P4000 R1250 T4000 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

M486 S0
M486 Acube20.stl
M486 S-1

;TYPE:Custom
M862.3 P "MINI" ; printer model check
M862.1 P0.4 A0 F0 ; nozzle check
M862.5 P2 ; g-code level check
M862.6 P"Input shaper" ; FW feature check
M115 U6.4.0+11974
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S60 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S60 ; wait for bed temp
M569 S1 X Y ; set stealthchop for X Y
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling
M104 S230 ; set extruder temp
G92 E0

G1 X0 Y-2 Z3 F2400

M109 S230 ; wait for extruder temp

; intro line
G1 X10 Z0.2 F1000
G1 X70 E8 F900
G1 X140 E10 F700
G92 E0

M569 S0 X Y ; set spreadcycle for X Y
M204 T4000 ; restore travel acceleration
M572 W0.06 ; set smooth time
M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.036
M572 S0.27
M107
; --- toolpaths removed for test fixture ---
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z22 F720 ; Move print head up
G1 X170 Y170 F4200 ; park print head
G1 Z70 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M572 S0 ; reset PA
M569 S1 X Y ; reset to stealthchop for X Y
M84 ; disable motors
; max_layer_z = 20
M73 P100 R0
M73 Q100 S0
; prusaslicer_json_config = begin
; {
;   "general": {
;     "producer": "PrusaSlicer",
;     "producer_version": "3.0.0-alpha11",
;     "time": "2026-09-13T12:12:32Z"
;   },
;   "config": {
;     "presets": {
;       "vendor": "PrusaResearch",
;       "version": "1.0.11",
;       "repo_id": "prusa-research-fff"
;     },
;     "printer": {
;       "config_id": "ab6b8840-d39c-4568-9b5b-0004bce8b975",
;       "printer_id": "MINI",
;       "vendor_id": "PrusaResearch",
;       "repo_id": "prusa-research-fff",
;       "repo_version": "1.0.11",
;       "config_name": "Prusa MINI 0.4",
;       "config_short_name": "Prusa MINI 0.4",
;       "technology": "fff",
;       "model": "MINI",
;       "base_model": "MINI",
;       "tool_count": 1,
;       "features": {"auxiliary_travel_anchor_x": -1.0, "supports_mmu_06_nozzle": false, "supports_025_nozzle": true, "auxiliary_travel_anchor_y": -1.0, "planetary_gearbox": false, "bed_segments_x": 1.0, "bed_segments_y": 1.0, "input_shaper": true, "multi_extruder": false, "supports_03_nozzle": false, "supports_04_nozzle": true, "supports_05_nozzle": false, "supports_06_nozzle": true, "supports_08_nozzle": true, "supports_high_flow_nozzle": false, "supports_mmu_025_nozzle": false, "supports_mmu_03_nozzle": false, "supports_mmu_04_nozzle": false, "supports_mmu_05_nozzle": false, "supports_tool_preheating": false, "supports_mmu_08_nozzle": false, "supports_non_high_flow_nozzle": true},
;       "tools": {"0": {"type": "print_head", "id": "0.4", "name": "0.4", "features": {"nozzle_diameter": 0.4, "nozzle_high_flow": false}, "slicer_material": {"id": "sFKqRDTTSgCK5uQeeDZjkg", "type": "PLA", "features": {}}, "material_package_instance": {"package": {"material": {"type": "PLA"}}}}},
;       "sheet": {"id": "pei_smooth", "name": "PEI Smooth", "type": "pei_smooth", "features": {"cold": false}},
;       "legacy_printer_model": "MINI",
;       "bed_model": "mini_bed.stl",
;       "bed_texture": "mini.svg",
;       "thumbnail": "MINI_thumbnail.svg"
;     }
;   },
;   "presets": {
;     "print_settings": {
;       "arc_fitting": "emit_center",
;       "automatic_extrusion_widths": false,
;       "automatic_infill_combination": false,
;       "automatic_infill_combination_max_layer_height": {"value": 100.0, "is_percent": true},
;       "avoid_crossing_curled_overhangs": false,
;       "avoid_crossing_perimeters": false,
;       "avoid_crossing_perimeters_max_detour": 0.0,
;       "bed_temperature_extruder": 0,
;       "bottom_fill_pattern": "monotonic",
;       "bottom_solid_layers": 4,
;       "bottom_solid_min_thickness": 0.5,
;       "bridge_acceleration": 1500.0,
;       "bridge_angle": 0.0,
;       "bridge_flow_ratio": 1.0,
;       "bridge_speed": 50.0,
;       "brim_separation": 0.1,
;       "brim_type": "no_brim",
;       "brim_width": 5.0,
;       "complete_objects": false,
;       "custom_parameters_print": "",
;       "default_acceleration": 2000.0,
;       "default_material": "Prusament PLA",
;       "default_tool_print": "",
;       "deretract_speed": 40.0,
;       "dont_support_bridges": false,
;       "draft_shield": "disabled",
;       "elefant_foot_compensation": 0.2,
;       "enable_dynamic_overhang_speeds": true,
;       "ensure_vertical_shell_thickness": "enabled",
;       "external_perimeter_acceleration": 2000.0,
;       "external_perimeter_extrusion_width": {"value": 0.45, "is_percent": false},
;       "external_perimeter_speed": {"value": 140.0, "is_percent": false},
;       "external_perimeters_first": false,
;       "extra_perimeters": false,
;       "extra_perimeters_on_overhangs": false,
;       "extrusion_width": {"value": 0.45, "is_percent": false},
;       "fill_angle": 45.0,
;       "fill_density": {"value": 15.0, "is_percent": true},
;       "fill_pattern": "grid",
;       "first_layer_acceleration": 500.0,
;       "first_layer_acceleration_over_raft": 0.0,
;       "first_layer_external_perimeter_speed": {"value": 0.0, "is_percent": false},
;       "first_layer_extrusion_width": {"value": 0.5, "is_percent": false},
;       "first_layer_gap_fill_speed": {"value": 0.0, "is_percent": false},
;       "first_layer_height": {"value": 0.2, "is_percent": false},
;       "first_layer_infill_speed": {"value": 0.0, "is_percent": false},
;       "first_layer_perimeter_speed": {"value": 0.0, "is_percent": false},
;       "first_layer_solid_infill_speed": {"value": 45.0, "is_percent": false},
;       "first_layer_speed": {"value": 30.0, "is_percent": false},
;       "first_layer_speed_over_raft": {"value": 30.0, "is_percent": false},
;       "first_layer_support_material_speed": {"value": 0.0, "is_percent": false},
;       "first_layer_top_solid_infill_speed": {"value": 0.0, "is_percent": false},
;       "fuzzy_skin": "none",
;       "fuzzy_skin_point_dist": 0.8,
;       "fuzzy_skin_thickness": 0.3,
;       "gap_fill_enabled": true,
;       "gap_fill_speed": 80.0,
;       "gcode_comments": false,
;       "gcode_label_objects": "firmware",
;       "gcode_resolution": 0.008,
;       "gcode_substitutions": [],
;       "infill_acceleration": 4000.0,
;       "infill_anchor": {"value": 2.5, "is_percent": false},
;       "infill_anchor_max": {"value": 12.0, "is_percent": false},
;       "infill_every_layers": 1,
;       "infill_extruder": 1,
;       "infill_extrusion_width": {"value": 0.45, "is_percent": false},
;       "infill_first": false,
;       "infill_overlap": {"value": 15.0, "is_percent": true},
;       "infill_speed": 140.0,
;       "interface_shells": false,
;       "interlocking_beam": false,
;       "interlocking_beam_layer_count": 2,
;       "interlocking_beam_width": 0.8,
;       "interlocking_boundary_avoidance": 2,
;       "interlocking_depth": 2,
;       "interlocking_orientation": 22.5,
;       "ironing": false,
;       "ironing_flowrate": {"value": 15.0, "is_percent": true},
;       "ironing_spacing": 0.1,
;       "ironing_speed": 15.0,
;       "ironing_type": "top",
;       "layer_height": 0.2,
;       "max_layer_height": 0.25,
;       "max_print_speed": 200.0,
;       "max_volumetric_extrusion_rate_slope_negative": 0.0,
;       "max_volumetric_extrusion_rate_slope_positive": 0.0,
;       "max_volumetric_speed": 0.0,
;       "min_bead_width": {"value": 85.0, "is_percent": true},
;       "min_feature_size": {"value": 25.0, "is_percent": true},
;       "min_layer_height": 0.07,
;       "min_skirt_length": 4.0,
;       "mmu_segmented_region_interlocking_depth": 0.0,
;       "mmu_segmented_region_max_width": 0.0,
;       "notes": "",
;       "only_one_perimeter_first_layer": false,
;       "only_retract_when_crossing_perimeters": false,
;       "ooze_prevention": false,
;       "output_filename_format": "{input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode",
;       "over_bridge_speed": {"value": 50.0, "is_percent": true},
;       "overhang_speed_0": {"value": 15.0, "is_percent": false},
;       "overhang_speed_1": {"value": 20.0, "is_percent": false},
;       "overhang_speed_2": {"value": 25.0, "is_percent": false},
;       "overhang_speed_3": {"value": 60.0, "is_percent": false},
;       "overhangs": true,
;       "perimeter_acceleration": 2500.0,
;       "perimeter_extruder": 1,
;       "perimeter_extrusion_width": {"value": 0.45, "is_percent": false},
;       "perimeter_generator": "arachne",
;       "perimeter_speed": 140.0,
;       "perimeters": 2,
;       "post_process": [],
;       "raft_contact_distance": 0.2,
;       "raft_expansion": 1.5,
;       "raft_first_layer_density": {"value": 80.0, "is_percent": true},
;       "raft_first_layer_expansion": 3.0,
;       "raft_layers": 0,
;       "resolution": 0.0,
;       "retract_before_travel": 1.5,
;       "retract_before_wipe": {"value": 0.0, "is_percent": true},
;       "retract_layer_change": true,
;       "retract_length": 2.5,
;       "retract_length_toolchange": 0.0,
;       "retract_lift": 0.2,
;       "retract_lift_above": 0.0,
;       "retract_lift_below": 179.0,
;       "retract_restart_extra": 0.0,
;       "retract_restart_extra_toolchange": 0.0,
;       "retract_speed": 70.0,
;       "scarf_seam_entire_loop": false,
;       "scarf_seam_length": 20.0,
;       "scarf_seam_max_segment_length": 1.0,
;       "scarf_seam_on_inner_perimeters": false,
;       "scarf_seam_only_on_smooth": true,
;       "scarf_seam_placement": "nowhere",
;       "scarf_seam_start_height": {"value": 0.0, "is_percent": true},
;       "seam_gap_distance": {"value": 15.0, "is_percent": true},
;       "seam_position": "aligned",
;       "single_extruder_multi_material_priming": false,
;       "skirt_distance": 6.0,
;       "skirt_height": 1,
;       "skirts": 0,
;       "slice_closing_radius": 0.049,
;       "slicing_mode": "regular",
;       "small_perimeter_speed": {"value": 140.0, "is_percent": false},
;       "solid_infill_acceleration": 4000.0,
;       "solid_infill_below_area": 0.0,
;       "solid_infill_every_layers": 0,
;       "solid_infill_extruder": 1,
;       "solid_infill_extrusion_width": {"value": 0.45, "is_percent": false},
;       "solid_infill_speed": {"value": 140.0, "is_percent": false},
;       "spiral_vase": false,
;       "staggered_inner_seams": false,
;       "standby_temperature_delta": -110,
;       "support_material": "enforcers_only",
;       "support_material_angle": 0.0,
;       "support_material_bottom_contact_distance": 0.0,
;       "support_material_bottom_interface_layers": 0,
;       "support_material_buildplate_only": false,
;       "support_material_closing_radius": 2.0,
;       "support_material_contact_distance": 0.2,
;       "support_material_enforce_layers": 0,
;       "support_material_extruder": 0,
;       "support_material_extrusion_width": {"value": 0.4, "is_percent": false},
;       "support_material_first_layer_density": {"value": 80.0, "is_percent": true},
;       "support_material_first_layer_expansion": 3.0,
;       "support_material_interface_contact_loops": false,
;       "support_material_interface_extruder": 0,
;       "support_material_interface_layers": 3,
;       "support_material_interface_pattern": "auto",
;       "support_material_interface_spacing": 0.2,
;       "support_material_interface_speed": {"value": 50.0, "is_percent": true},
;       "support_material_pattern": "rectilinear",
;       "support_material_spacing": 2.0,
;       "support_material_speed": 100.0,
;       "support_material_style": "snug",
;       "support_material_synchronize_layers": false,
;       "support_material_threshold": 40,
;       "support_material_with_sheath": false,
;       "support_material_xy_spacing": {"value": 80.0, "is_percent": true},
;       "support_tree_angle": 40.0,
;       "support_tree_angle_slow": 25.0,
;       "support_tree_branch_diameter": 2.0,
;       "support_tree_branch_diameter_angle": 5.0,
;       "support_tree_branch_diameter_double_wall": 8.0,
;       "support_tree_branch_distance": 1.0,
;       "support_tree_tip_diameter": 0.8,
;       "support_tree_top_rate": {"value": 30.0, "is_percent": true},
;       "thick_bridges": false,
;       "thin_walls": false,
;       "toolchange_ordering": "optimized",
;       "top_fill_pattern": "monotoniclines",
;       "top_infill_extrusion_width": {"value": 0.42, "is_percent": false},
;       "top_one_perimeter_type": "none",
;       "top_solid_infill_acceleration": 1000.0,
;       "top_solid_infill_speed": {"value": 80.0, "is_percent": false},
;       "top_solid_layers": 5,
;       "top_solid_min_thickness": 0.7,
;       "travel_acceleration": 4000.0,
;       "travel_lift_before_obstacle": false,
;       "travel_max_lift": 1.5,
;       "travel_ramping_lift": false,
;       "travel_short_distance_acceleration": 250.0,
;       "travel_slope": 1.0,
;       "travel_speed": 400.0,
;       "travel_speed_z": 12.0,
;       "wall_distribution_count": 1,
;       "wall_transition_angle": 10.0,
;       "wall_transition_filter_deviation": {"value": 25.0, "is_percent": true},
;       "wall_transition_length": {"value": 100.0, "is_percent": true},
;       "wipe": false,
;       "wipe_tower": true,
;       "wipe_tower_acceleration": 0.0,
;       "wipe_tower_bridging": 10.0,
;       "wipe_tower_brim_width": 3.0,
;       "wipe_tower_cone_angle": 25.0,
;       "wipe_tower_extra_flow": {"value": 250.0, "is_percent": true},
;       "wipe_tower_extra_spacing": {"value": 110.0, "is_percent": true},
;       "wipe_tower_extruder": 0,
;       "wipe_tower_no_sparse_layers": false,
;       "wipe_tower_width": 60.0,
;       "xy_size_compensation": 0.0
;     },
;     "toolprint_settings": {},
;     "printer_settings": {
;       "autoemit_temperature_commands": true,
;       "bed_custom_model": "",
;       "bed_custom_texture": "",
;       "bed_shape": [[0.0, 0.0], [180.0, 0.0], [180.0, 180.0], [0.0, 180.0]],
;       "before_layer_gcode": ";BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\nM201 X{interpolate_table(extruded_weight_total, (0,4000), (1000,1700), (20000,1700))} Y{interpolate_table(extruded_weight_total, (0,4000), (1000,1700), (20000,1700))}\n",
;       "between_objects_gcode": "",
;       "binary_gcode": true,
;       "color_change_gcode": "M600",
;       "cooling_tube_length": 20.0,
;       "cooling_tube_retraction": 45.0,
;       "custom_parameters_printer": "",
;       "default_print": "0.15mm QUALITY",
;       "enable_pressure_advance_during_ramming": false,
;       "end_gcode": "{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X170 Y170 F4200 ; park print head\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+50, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM572 S0 ; reset PA\nM569 S1 X Y ; reset to stealthchop for X Y\nM84 ; disable motors\n; max_layer_z = [max_layer_z]",
;       "extra_loading_move": -52.0,
;       "extruder_clearance_height": 20.0,
;       "extruder_clearance_radius": 20.0,
;       "extruder_offset": [[0.0, 0.0]],
;       "filament_change_time": 0.0,
;       "gcode_flavor": "marlin2",
;       "high_current_on_filament_swap": false,
;       "layer_gcode": ";AFTER_LAYER_CHANGE\n;[layer_z]\n{if ! spiral_vase}M74 W[extruded_weight_total]{endif}\n",
;       "machine_limits_usage": "emit_to_gcode",
;       "machine_max_acceleration_e": [5000.0, 5000.0],
;       "machine_max_acceleration_extruding": [4000.0, 2500.0],
;       "machine_max_acceleration_retracting": [1250.0, 1250.0],
;       "machine_max_acceleration_travel": [4000.0, 2500.0],
;       "machine_max_acceleration_x": [4000.0, 2500.0],
;       "machine_max_acceleration_y": [4000.0, 2500.0],
;       "machine_max_acceleration_z": [400.0, 400.0],
;       "machine_max_feedrate_e": [120.0, 120.0],
;       "machine_max_feedrate_x": [400.0, 180.0],
;       "machine_max_feedrate_y": [400.0, 180.0],
;       "machine_max_feedrate_z": [12.0, 12.0],
;       "machine_max_jerk_e": [10.0, 10.0],
;       "machine_max_jerk_x": [8.0, 8.0],
;       "machine_max_jerk_y": [8.0, 8.0],
;       "machine_max_jerk_z": [2.0, 2.0],
;       "machine_max_junction_deviation": [0.0, 0.0],
;       "machine_min_extruding_rate": [0.0, 0.0],
;       "machine_min_travel_rate": [0.0, 0.0],
;       "max_print_height": 180.0,
;       "multimaterial_purging": 80.0,
;       "parking_pos_retraction": 84.0,
;       "pause_print_gcode": "M601",
;       "prefer_clockwise_movements": false,
;       "printer_model": "MINI",
;       "printer_notes": "",
;       "printer_technology": "FFF",
;       "printer_variant": "",
;       "printer_vendor": "",
;       "remaining_times": true,
;       "silent_mode": true,
;       "single_extruder_multi_material": false,
;       "start_gcode": "M862.3 P \"MINI\" ; printer model check\nM862.1 P[nozzle_diameter] A{(filament_abrasive[0] ? 1 : 0)} F{(nozzle_high_flow[0] ? 1 : 0)} ; nozzle check\nM862.5 P2 ; g-code level check\nM862.6 P\"Input shaper\" ; FW feature check\nM115 U6.4.0+11974\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM569 S1 X Y ; set stealthchop for X Y\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\n\nG1 X0 Y-2 Z3 F2400\n\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X10 Z0.2 F1000\nG1 X70 E8 F900\nG1 X140 E10 F700\nG92 E0\n\nM569 S0 X Y ; set spreadcycle for X Y\nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM572 W0.06 ; set smooth time\nM221 S95 ; set flow\n",
;       "stuck_filament_detection": false,
;       "template_custom_gcode": "",
;       "thumbnails": "16x16/QOI, 220x124/QOI, 200x240/QOI, 380x285/PNG",
;       "thumbnails_format": "PNG",
;       "toolchange_gcode": "",
;       "use_firmware_retraction": false,
;       "use_relative_e_distances": true,
;       "use_volumetric_e": false,
;       "variable_layer_height": true,
;       "z_offset": 0.0
;     },
;     "filament_settings": {
;       "bed_temperature": [60],
;       "bridge_fan_speed": [100],
;       "chamber_minimal_temperature": [0],
;       "chamber_temperature": [0],
;       "cooling": [true],
;       "cooling_perimeter_transition_distance": [10.0],
;       "cooling_slowdown_logic": ["uniform_cooling"],
;       "custom_parameters_filament": [""],
;       "disable_fan_first_layers": [1],
;       "enable_dynamic_fan_speeds": [false],
;       "end_filament_gcode": ["; Filament-specific end gcode"],
;       "extrusion_multiplier": [1.0],
;       "fan_always_on": [true],
;       "fan_below_layer_time": [100],
;       "filament_abrasive": [false],
;       "filament_colour": [""],
;       "filament_cooling_final_speed": [3.5],
;       "filament_cooling_initial_speed": [10.0],
;       "filament_cooling_moves": [2],
;       "filament_cost": [27.99],
;       "filament_density": [1.24],
;       "filament_diameter": [1.75],
;       "filament_flush_speed": [0.0],
;       "filament_flush_volume": [0.0],
;       "filament_infill_max_crossing_speed": [0.0],
;       "filament_infill_max_speed": [0.0],
;       "filament_loading_speed": [10.0],
;       "filament_loading_speed_start": [50.0],
;       "filament_max_volumetric_speed": [15.0],
;       "filament_minimal_purge_on_wipe_tower": [15.0],
;       "filament_multitool_ramming": [false],
;       "filament_multitool_ramming_flow": [10.0],
;       "filament_multitool_ramming_volume": [10.0],
;       "filament_notes": [""],
;       "filament_purge_multiplier": [{"value": 100.0, "is_percent": true}],
;       "filament_ramming_initial_delay": [0.0],
;       "filament_ramming_parameters": ["250 100 40.1613 40.3548 40.4516 40.3548 40.2581| 0.05 40.1483 0.45 40.3419 0.95 40.3419 1.45 40.3419 1.95 40.3419 2.45 40.3419 2.95 40.3419 3.45 40.3419 3.95 40.3419 4.45 40.3419 4.95 40.3419"],
;       "filament_ramming_temperature_delta": [0],
;       "filament_shrinkage_compensation_xy": [{"value": 0.0, "is_percent": true}],
;       "filament_shrinkage_compensation_z": [{"value": 0.0, "is_percent": true}],
;       "filament_soluble": [false],
;       "filament_spool_weight": [278.0],
;       "filament_stamping_distance": [45.0],
;       "filament_stamping_loading_speed": [29.0],
;       "filament_toolchange_delay": [0.0],
;       "filament_type": ["PLA"],
;       "filament_unloading_speed": [100.0],
;       "filament_unloading_speed_start": [100.0],
;       "filament_vendor": ["Prusa Polymers"],
;       "first_layer_bed_temperature": [60],
;       "first_layer_temperature": [230],
;       "full_fan_speed_layer": [3],
;       "idle_temperature": [null],
;       "max_fan_speed": [100],
;       "min_fan_speed": [100],
;       "min_print_speed": [15.0],
;       "overhang_fan_speed_0": [0],
;       "overhang_fan_speed_1": [0],
;       "overhang_fan_speed_2": [0],
;       "overhang_fan_speed_3": [0],
;       "pressure_advance": ["enabled"],
;       "pressure_advance_value": [0.27],
;       "slowdown_below_layer_time": [15],
;       "start_filament_gcode": ["M900 K0.036"],
;       "temperature": [225],
;       "travel_max_lift": [0.6],
;       "travel_ramping_lift": [true],
;       "travel_slope": [1.0]
;     },
;     "project_settings": {
;       "extruder_colour": [
;         "#FF8000"
;       ],
;       "wiping_volumes_matrix": [0.0, 140.0, 140.0, 140.0, 140.0, 140.0, 0.0, 140.0, 140.0, 140.0, 140.0, 140.0, 0.0, 140.0, 140.0, 140.0, 140.0, 140.0, 0.0, 140.0, 140.0, 140.0, 140.0, 140.0, 0.0],
;       "wiping_volumes_use_custom_matrix": false
;     }
;   },
;   "project": {
;     "id": "b8790fcc-ae8b-4c42-b466-08222fec3d1f",
;     "version": 0
;   },
;   "stats": null
; }
;
; prusaslicer_json_config = end
; objects_info = {"objects":[{"name":"cube20.stl","polygon":[[100.000,100.000],[80.000,100.000],[80.000,80.000],[100.000,80.000]]}]}
; filament used [mm] = 1292.33
; filament used [cm3] = 3.11
; filament used [g] = 3.85
; filament cost = 0.11
; total filament used [g] = 3.85
; total filament cost = 0.11
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 26m 41s
; estimated printing time (silent mode) = 26m 55s
; estimated first layer printing time (normal mode) = 37s
; estimated first layer printing time (silent mode) = 37s

; prusaslicer_config = begin
; arc_fitting = emit_center
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\nM201 X{interpolate_table(extruded_weight_total, (0,4000), (1000,1700), (20000,1700))} Y{interpolate_table(extruded_weight_total, (0,4000), (1000,1700), (20000,1700))}\n
; between_objects_gcode =
; binary_gcode = 1
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1500
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 50
; brim_separation = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights =
; compatible_printers_condition_cummulative =
; complete_objects = 0
; cooling = 1
; cooling_perimeter_transition_distance = 10
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 20
; cooling_tube_retraction = 45
; custom_parameters_filament = ""
; custom_parameters_print =
; custom_parameters_printer =
; default_acceleration = 2000
; default_filament_profile =
; default_print_profile =
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; enable_pressure_advance_during_ramming = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X170 Y170 F4200 ; park print head\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+50, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM572 S0 ; reset PA\nM569 S1 X Y ; reset to stealthchop for X Y\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 2000
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 140
; external_perimeters_first = 0
; extra_loading_move = -52
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FF8000
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_change_time = 0
; filament_colour = ""
; filament_cooling_final_speed = 3.5
; filament_cooling_initial_speed = 10
; filament_cooling_moves = 2
; filament_cost = 27.99
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_flush_speed = 0
; filament_flush_volume = 0
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_loading_speed = 10
; filament_loading_speed_start = 50
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_initial_delay = 0
; filament_ramming_parameters = "250 100 40.1613 40.3548 40.4516 40.3548 40.2581| 0.05 40.1483 0.45 40.3419 0.95 40.3419 1.45 40.3419 1.95 40.3419 2.45 40.3419 2.95 40.3419 3.45 40.3419 3.95 40.3419 4.45 40.3419 4.95 40.3419"
; filament_ramming_temperature_delta = 0
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = ""
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 278
; filament_stamping_distance = 45
; filament_stamping_loading_speed = 29
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = 0.6
; filament_travel_ramping_lift = 1
; filament_travel_slope = 1
; filament_type = PLA
; filament_unloading_speed = 100
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; filament_wipe = nil
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 500
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.2
; first_layer_infill_speed = 0
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 230
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 80
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = firmware
; gcode_resolution = 0.008
; gcode_substitutions =
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 4000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 140
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\n{if ! spiral_vase}M74 W[extruded_weight_total]{endif}\n
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 4000,2500
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 4000,2500
; machine_max_acceleration_x = 4000,2500
; machine_max_acceleration_y = 4000,2500
; machine_max_acceleration_z = 400,400
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 400,180
; machine_max_feedrate_y = 400,180
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 10,10
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 2,2
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 180
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 80
; notes =
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; over_bridge_speed = 50%
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 20
; overhang_speed_2 = 25
; overhang_speed_3 = 60
; overhangs = 1
; parking_pos_retraction = 84
; pause_print_gcode = M601
; perimeter_acceleration = 2500
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 140
; perimeters = 2
; physical_printer_settings_id =
; post_process =
; prefer_clockwise_movements = 0
; print_settings_id =
; printer_model = MINI
; printer_notes =
; printer_settings_id =
; printer_technology = FFF
; printer_variant =
; printer_vendor =
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 80%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 140
; solid_infill_acceleration = 4000
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 140
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -110
; start_filament_gcode = "M900 K0.036"
; start_gcode = M862.3 P "MINI" ; printer model check\nM862.1 P[nozzle_diameter] A{(filament_abrasive[0] ? 1 : 0)} F{(nozzle_high_flow[0] ? 1 : 0)} ; nozzle check\nM862.5 P2 ; g-code level check\nM862.6 P"Input shaper" ; FW feature check\nM115 U6.4.0+11974\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM569 S1 X Y ; set stealthchop for X Y\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\n\nG1 X0 Y-2 Z3 F2400\n\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X10 Z0.2 F1000\nG1 X70 E8 F900\nG1 X140 E10 F700\nG92 E0\n\nM569 S0 X Y ; set spreadcycle for X Y\nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM572 W0.06 ; set smooth time\nM221 S95 ; set flow\n
; stuck_filament_detection = 0
; support_material = enforcers_only
; support_material_angle = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.4
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 3
; support_material_interface_pattern = auto
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 50%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 100
; support_material_style = snug
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 8
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 30%
; temperature = 225
; template_custom_gcode =
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 16x16/QOI, 220x124/QOI, 200x240/QOI, 380x285/PNG
; thumbnails_format = PNG
; toolchange_gcode =
; toolchange_ordering = optimized
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.42
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 1000
; top_solid_infill_speed = 80
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 4000
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 250
; travel_slope = 0
; travel_speed = 400
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 3
; wipe_tower_cone_angle = 25
; wipe_tower_extra_flow = 250%
; wipe_tower_extra_spacing = 110%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end

