; generated by PrusaSlicer 2.9.2 on 2026-09-13 at 12:26:02 UTC

;

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.56mm

M201 X2500 Y2500 Z800 E2500 ; sets maximum accelerations, mm/sec^2
M203 X250 Y250 Z8 E80 ; sets maximum feedrates, mm / sec
M204 S2500 T2500 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X10.00 Y10.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28                                        ; move X/Y/Z to min endstops
G1 Z0.28                                   ; lift nozzle a bit
G92 E0
G1 Y3 F1800                                    ; zero the extruded length
G1 X60  E25 F500                       ; Extrude 25mm of filament in a 5cm line.
G92 E0                                     ; zero the extruded length again
G1 E-2 F500                                ; Retract a little
G1 X70 F4000                              ; Quickly wipe away from the filament line
M117
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
M107
; --- toolpaths removed for test fixture ---
M107
;TYPE:Custom
M104 S0                                    ; Extruder off
M140 S0                                    ; Heatbed off
M107                                       ; Fan off
G91                                        ; relative positioning
G1 E-5 F3000
G1 Z+0.3 F3000                             ; lift print head
G28 X0  F3000
M84                                        ; disable stepper motors
; objects_info = {"objects":[]}
; filament used [mm] = 1332.37
; filament used [cm3] = 3.20
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 10m 42s
; estimated first layer printing time (normal mode) = 26s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,220x0,220x220,0x220
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ; BEFORE_LAYER_CHANGE [layer_num] @ [layer_z]mm
; between_objects_gcode =
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 2500
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.85
; bridge_speed = 40
; brim_separation = 0.16
; brim_type = no_brim
; brim_width = 3
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights =
; compatible_printers_condition =
; compatible_prints_condition =
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Anycubic PLA @MEGA0"
; default_print_profile = 0.20mm NORMAL @MEGA0
; deretract_speed = 0
; disable_fan_first_layers = 2
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = ""
; end_gcode = M104 S0                                    ; Extruder off \nM140 S0                                    ; Heatbed off \nM107                                       ; Fan off \nG91                                        ; relative positioning \nG1 E-5 F3000  \nG1 Z+0.3 F3000                             ; lift print head \nG28 X0  F3000\nM84                                        ; disable stepper motors
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 50%
; external_perimeters_first = 1
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.42
; fan_always_on = 0
; fan_below_layer_time = 600
; filament_abrasive = 0
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = 15%
; filament_settings_id = "Kobra2-PLA Parameter"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; filament_wipe = nil
; fill_angle = 45
; fill_density = 10%
; fill_pattern = grid
; first_layer_acceleration = 2000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 200%
; first_layer_height = 0.28
; first_layer_infill_speed = 0
; first_layer_speed = 50
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 100
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = disabled
; gcode_resolution = 0.012
; gcode_substitutions =
; high_current_on_filament_swap = 0
; host_type = octoprint
; idle_temperature = nil
; infill_acceleration = 3000
; infill_anchor = 10
; infill_anchor_max = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 150
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ; AFTER_LAYER_CHANGE [layer_num] @ [layer_z]mm
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 2500
; machine_max_acceleration_extruding = 2500
; machine_max_acceleration_retracting = 2500
; machine_max_acceleration_travel = 3000,1250
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 800
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 250
; machine_max_feedrate_y = 250
; machine_max_feedrate_z = 8
; machine_max_jerk_e = 10
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.28
; max_print_height = 250
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.04
; min_print_speed = 25
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes =
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}-{layer_height}-{print_time}.gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 2500
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = classic
; perimeter_speed = 150
; perimeters = 3
; physical_printer_settings_id =
; post_process =
; prefer_clockwise_movements = 0
; print_settings_id = Kobra2-PLA Parameter
; printer_model =
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_ANYCUBIC\nPRINTER_MODEL_MEGA0
; printer_settings_id = Kobra2-PLA Parameter
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor =
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 4
; raft_layers = 0
; remaining_times = 0
; resolution = 0.012
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 2
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 80
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 50%
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 150
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28                                        ; move X/Y/Z to min endstops\nG1 Z0.28                                   ; lift nozzle a bit \nG92 E0 \nG1 Y3 F1800                                    ; zero the extruded length \nG1 X60  E25 F500                       ; Extrude 25mm of filament in a 5cm line. \nG92 E0                                     ; zero the extruded length again \nG1 E-2 F500                                ; Retract a little \nG1 X70 F4000                              ; Quickly wipe away from the filament line\nM117
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.25
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear-grid
; support_material_spacing = 2.5
; support_material_speed = 50
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 10
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 30%
; temperature = 195
; template_custom_gcode =
; thick_bridges = 0
; thin_walls = 1
; thumbnails =
; thumbnails_format = PNG
; toolchange_gcode =
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.42
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 120
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 120
; travel_speed_z = 120
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
