using System.Text.RegularExpressions;

namespace Slic3rPostProcessingUploader.Services.Parsers.FLSunSlicer
{
    internal partial class FLSunParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "FLSunSlicer";
        [GeneratedRegex(@"generated by FlsunSlicer (.+) on", RegexOptions.IgnoreCase | RegexOptions.Multiline)]
        private static partial Regex VersionRegex();
        protected override Regex SlicerVersionRegex => VersionRegex();
        protected override INoteTemplate CreateDefaultTemplate() => EmbeddedNoteTemplate.Default("FLSunSlicer");

        public static bool IsFLSunSlicer(string gcode)
        {
            return gcode.Contains("generated by FlsunSlicer", StringComparison.Ordinal);
        }
    }
}
