using System.Text.RegularExpressions;

namespace Slic3rPostProcessingUploader.Services.Parsers.OrcaSlicer
{
    internal partial class OrcaParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "OrcaSlicer";
        [GeneratedRegex(@"generated by OrcaSlicer (.+) on", RegexOptions.IgnoreCase | RegexOptions.Multiline)]
        private static partial Regex VersionRegex();
        protected override Regex SlicerVersionRegex => VersionRegex();
        protected override INoteTemplate CreateDefaultTemplate() => EmbeddedNoteTemplate.Default("OrcaSlicer");
        protected override bool SupportsMultiFilament => true;

        public static bool IsOrcaSlicer(string gcode)
        {
            return gcode.Contains("generated by OrcaSlicer", StringComparison.Ordinal);
        }
    }
}
